### ISSUE TITLE
Support expression as a variable?

### ISSUE THREAD

**Issue by askfor** [ezylang/EvalEx#229] opened 2019-11-15 01:41 UTC
Can we support expression as a variable? Or is there any reason it was not meant to be supported?

```
Expression subExpression = new Expression("1 + c").with("c", "2");
Expression expression = new Expression("a * b");
expression.with("a", "1")
                 .and("b", subExpression)
	         .eval();
```

**Comment by askfor** [comment] 2019-11-15 01:50
If expression as a variable is supported, we can get all expressions from the root expression.

**Comment by RobertZenz** [comment] 2019-11-15 08:06
This is most likely a duplicate of #9, and there is #143 which I was completely not aware of.

Though, the closure of #9 it is now 5 years ago and a few things have changed since then, I would be in favor of reevaluating this idea (evaluating, mind you).

However, implementing this might be a little bit more complicated than one might assume on first sight.

**Comment by askfor** [comment] 2019-11-15 08:57
I'm aware of #143's feature, It helped a little bit, with it we can introduce explanatory variables to make the expression easier to understand.
But sometimes some calculate process is too complicated, so split it into multiple expressions helps a lot ( and with the ability to pull them out as a whole)

I didn't find #9 before, I agree that it's not hard to get this done on a higher level. if this feature was not intended to add, I'll just wrap Expression to make it work.

Thanks.

**Comment by RobertZenz** [comment] 2019-11-15 09:20
I think the quickest way for you to get that would be to have a custom `LazyNumber` implementation, something along these lines:

```java
Expression expression = new Expression("a+b")
        .with("a", new LazyExpression("1+1"))
        .with("b", "5");

public class LazyExpression implements LazyNumber {
    protected String expression = null;
    
    public LazyExpression(String expression) {
        this.expression = expression;
    }
    public BigDecimal eval() {
        return new Expression(expression).eval();
    }
    ...
}
```

However, there is no way to get variables from an `Expression` once they have been added. I believe my "Scope" PR contained such possibilities, but that one never got finished.

**Comment by askfor** [comment] 2019-11-15 11:21
Thanks, I'll gonna save those variables in the wrapper, sorta like this. But it was not tested yet.

```
public class Formula {

    private Expression expression;
    private TreeMap<String, Parameter> vars = new TreeMap<>();

    private Formula(String expr) {
        expression = new Expression(expr);
    }
    public Formula with(String name, Formula formula) {
        vars.put(name, new Parameter(name, formula.expression.eval(), formula.expression.getExpression()));
        expression.with(name, new LazyNumber() {
            @Override
            public BigDecimal eval() {
                return formula.expression.eval();
            }

            @Override
            public String getString() {
                return formula.expression.getExpression();
            }
        });
        return this;
    }
}
```

**Comment by RobertZenz** [comment] 2019-11-15 11:29
Looks good, minor detail is that you most likely don't want a `TreeMap`, a simple `HashMap` should suffice.

**Comment by uklimaschewski** [comment] 2021-05-26 11:06
I'll close this. If it is still wanted, please re-open and submit a PR

**Comment by askfor** [comment] 2022-12-16 14:30
Hi, It seems LazyNumber was removed in 3.x, this approch is no longer viable.
Is there any way to do this in 3.x?

> Thanks, I'll gonna save those variables in the wrapper, sorta like this. But it was not tested yet. However, variables was private in 2.1, it was protected in the master branch.
> 
> ```
> public class Formula {
> 
>     private Expression expression;
>     private TreeMap<String, Parameter> vars = new TreeMap<>();
> 
>     private Formula(String expr) {
>         expression = new Expression(expr);
>     }
>     public Formula with(String name, Formula formula) {
>         vars.put(name, new Parameter(name, formula.expression.eval(), formula.expression.getExpression()));
>         expression.with(name, new LazyNumber() {
>             @Override
>             public BigDecimal eval() {
>                 return formula.expression.eval();
>             }
> 
>             @Override
>             public String getString() {
>                 return formula.expression.getExpression();
>             }
>         });
>         return this;
>     }
> }
> ```

**Comment by uklimaschewski** [comment] 2022-12-16 14:59
With 3.x, there is the possibility of passing sub-expressions as parameters directly, see the [documentation for EXPRESSION_NODE data type](https://ezylang.github.io/EvalEx/concepts/datatypes.html#expression_node)

Does this what you are aiming for?

Example:

```java
Expression expression = new Expression("a*b");

ASTNode subExpression = expression.createExpressionNode("4+3");

EvaluationValue result = expression
    .with("a", 2)
    .and("b", subExpression)
    .evaluate();

System.out.println(result); // prints 14
```

**Comment by askfor** [comment] 2022-12-16 16:07
Hi, I've read about the ASTNode example in the document, but I think it has some differences.
With the previous implementation user can get the expression and variables of sub-expressions, it seems not possible with ASTNode.

What am I tring to achieve is to display expression, result and variables to user, some times the expression is too complicated, it'll be useful to break the expression to serval expressions. 
Can we support 'Expression' as a parameter for 'with' instead of(or along with) 'ASTNode'?

**Comment by uklimaschewski** [comment] 2022-12-17 09:07
Getting all the variables for a tree starting with an `ASTNode` is very easy, have a look at the code for `getUsedVariables()`.
And the expression itself is what you pass to the constructor or `createExpressionNode("a+b")`, so I think you have all at hand.

Maybe adding a public static `getUsedVariablesForASTNode(ASTNode root)`  convenient function or something like this could help you avoiding copying the code.

**Comment by askfor** [comment] 2022-12-18 03:49
```
Expression expression = new Expression( expressionString: "(a+b)*c");
ASTNode subExpression = expression.createExpressionNode("d+e");
EvaluationValue result = expression.with(variable: "a","1")
 and( "b", 2)
 and ("c", subExpression)
 and("d",  3)
 and ("e", 4)
.evaluate() ;
```
For example,I can get all varialbes ”a, b, c" via `expression.getUsedVariables()`. and can get the value of "a, b" via `expression.getDataAccessor().getData()`.
But I also want to get the expression and the evaluated value of "c" ( "d+e" and 7), it seems not possible atm?

And I seems to me `ASTNode` is more like a internal type,  Maybe add a new type such as `SubExpression ` for end user is more suitable IMO.

**Comment by uklimaschewski** [comment] 2022-12-25 08:52
There is also a way to work with subexpressions using two expressions. Here you have two expressions and can use all the methods, including `getUsedvariables()`:

```java
        Expression expression = new Expression("a+b+c");
        Expression subExpression = new Expression("a-x");

        Map<String, Object> variables = new HashMap<>();

        variables.put("a", 3);
        variables.put("b", subExpression.getAbstractSyntaxTree());
        variables.put("c", 4);
        variables.put("x", 1);

        assertThat(expression.withValues(variables).evaluate().getStringValue()).isEqualTo("9");

        assertThat(expression.getUsedVariables()).containsExactlyInAnyOrder("a", "b", "c");
        assertThat(subExpression.getUsedVariables()).containsExactlyInAnyOrder("a", "x");
```

**Comment by askfor** [comment] 2023-01-01 11:13
But there's no easy way to get the value of subExpression?

> There is also a way to work with subexpressions using two expressions. Here you have two expressions and can use all the methods, including `getUsedvariables()`:
> 
> ```java
>         Expression expression = new Expression("a+b+c");
>         Expression subExpression = new Expression("a-x");
> 
>         Map<String, Object> variables = new HashMap<>();
> 
>         variables.put("a", 3);
>         variables.put("b", subExpression.getAbstractSyntaxTree());
>         variables.put("c", 4);
>         variables.put("x", 1);
> 
>         assertThat(expression.withValues(variables).evaluate().getStringValue()).isEqualTo("9");
> 
>         assertThat(expression.getUsedVariables()).containsExactlyInAnyOrder("a", "b", "c");
>         assertThat(subExpression.getUsedVariables()).containsExactlyInAnyOrder("a", "x");
> ```

**Comment by askfor** [comment] 2023-01-01 11:31
Hi, it seems we can't get the value of subExpression easily(without put all those variables to subExpression again).
The result of `expression.getDataAccesor().getData("b")` is 0 instead of 2.

> There is also a way to work with subexpressions using two expressions. Here you have two expressions and can use all the methods, including `getUsedvariables()`:
> 
> ```java
>         Expression expression = new Expression("a+b+c");
>         Expression subExpression = new Expression("a-x");
> 
>         Map<String, Object> variables = new HashMap<>();
> 
>         variables.put("a", 3);
>         variables.put("b", subExpression.getAbstractSyntaxTree());
>         variables.put("c", 4);
>         variables.put("x", 1);
> 
>         assertThat(expression.withValues(variables).evaluate().getStringValue()).isEqualTo("9");
> 
>         assertThat(expression.getUsedVariables()).containsExactlyInAnyOrder("a", "b", "c");
>         assertThat(subExpression.getUsedVariables()).containsExactlyInAnyOrder("a", "x");
> ```

**Comment by uklimaschewski** [comment] 2023-01-01 14:29
The data storage is not part of the expression, but part of the configuration. By default each expression gets a new instance of a default configuration, which also has a new instance of the `MapBasedDataAccessior`, which holds the data in a `Map`.

If you want to share the configuration (and data) between different expression, you can create a common configuration and pass this to the expression constructor.

`expression.getDataAccessor().getData("b")`  will return the sub-expression, i.e. the root `ASTNode` of the expression, it will not be calculated automatically. (Remember: the `getData()` method returns an `EvaluationValue`, which can be a number, string, array, structure or a sub-expression (`ASTNode`).

Here's an extended example:
```java
    @Test
    void testSubExpression() throws ParseException, EvaluationException {

        // shared configuration, has a an instance of the data accessor
        ExpressionConfiguration configuration = ExpressionConfiguration.defaultConfiguration();

        Expression expression = new Expression("a+b+c", configuration);
        Expression subExpression = new Expression("a-x", configuration);

        Map<String, Object> variables = new HashMap<>();

        variables.put("a", 3);
        variables.put("b", subExpression.getAbstractSyntaxTree());
        variables.put("c", 4);
        variables.put("x", 1);

        assertThat(expression.withValues(variables).evaluate().getStringValue()).isEqualTo("9");

        assertThat(expression.getUsedVariables()).containsExactlyInAnyOrder("a", "b", "c");
        assertThat(subExpression.getUsedVariables()).containsExactlyInAnyOrder("a", "x");

        // all the data is accessible through expression
        assertThat(expression.getDataAccessor().getData("a").getStringValue()).isEqualTo("3");
        assertThat(expression.getDataAccessor().getData("b").getExpressionNode()).isEqualTo(subExpression.getAbstractSyntaxTree());
        assertThat(expression.getDataAccessor().getData("c").getStringValue()).isEqualTo("4");
        assertThat(expression.getDataAccessor().getData("x").getStringValue()).isEqualTo("1");

        // all the data is also accessible through subExpression
        assertThat(subExpression.getDataAccessor().getData("a").getStringValue()).isEqualTo("3");
        assertThat(subExpression.getDataAccessor().getData("b").getExpressionNode()).isEqualTo(subExpression.getAbstractSyntaxTree());
        assertThat(subExpression.getDataAccessor().getData("c").getStringValue()).isEqualTo("4");
        assertThat(subExpression.getDataAccessor().getData("x").getStringValue()).isEqualTo("1");

        // subExpression has to be evaluated manually
        assertThat(expression.evaluateSubtree(expression.getDataAccessor().getData("b").getExpressionNode()).getStringValue()).isEqualTo("2");

        // or in this case, simpler:
        assertThat(subExpression.evaluate().getStringValue()).isEqualTo("2");
    }

```

**Comment by askfor** [comment] 2023-01-07 06:16
Thanks, sharing configuration works.
And there's another question, why checked exception was introduced in 3.x while exceptions in 2.x were unchecked exception?

**Comment by uklimaschewski** [comment] 2023-01-07 10:20
Error behavior was a bit inconsistent in 2.x, There are now two exceptions that can be used to recover from possible failures.
One possible failure can occur when parsing an expression, in that case the `ParseException` is thrown. This exception is also thrown when the `validate()` method is called.

The other possible failure can occur when validating an expression, depending on the input values. In that case, an `EvaluationException` is thrown.

Both exceptions hold valuable information that can be given to a user so that he/she knows what went wrong at what exact position of the entered expression.

Both are checked exceptions, because both are predictable and a proper exception handling should be done by the calling system.

**Closed by uklimaschewski** 2023-01-07 10:20 UTC
Labels: question
