### ISSUE TITLE
2ab(a+b) => ParseException Undefined function 'ab'

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [ezylang/EvalEx#343] opened 2023-01-27 10:40 UTC
Why `2ab(a+b)` is not valid?
I got error
```
ParseException(super=BaseException(startPosition=2, endPosition=4, tokenString=ab, message=Undefined function 'ab'))
```

**Comment by RobertZenz** [comment] 2023-01-27 10:57
What would be the expected behavior?

**Comment by xuan-nguyen-swe** [comment] 2023-01-27 12:06
Hi @RobertZenz, I would expect that all expressions below are valid and have the same result:

`2ab(a+b)`
`2ab*(a+b)`
`2a*b*(a+b)`
`2*a*b*(a+b)`

If a is 3.5 and b is 2.5, the result should be 105 as I see in excel:
![image](https://user-images.githubusercontent.com/24372782/215082405-a486cec1-4f65-4130-b8b1-b3ca0ae72743.png)

This is how I am educated in schools.

Btw, I think this lib is one of the best open-source lib I found. I like it a lot.

**Comment by xuan-nguyen-swe** [comment] 2023-01-27 12:58
I think, the Implicit Multiplication feature is really buggy. A simple exp `2a` with a = 3.5 returns 3.5. I would expect 7 as result.
This feature should be tested more carefully, imo.

**Comment by uklimaschewski** [comment] 2023-01-29 10:39
Implicit multiplication is only possible, if there is a closing bracket or number literal in front of a closing bracket.
E.g. `2(a+b)`or `(a+b)(b+c)`.
Any letters in front of a opening bracket are treated as a function name.
Resolving `2ab` to `2*a*b` won't be possible, because the parser does not know the variables upfront. It can't recognize you mean `a*b` and not the variable `ab`.

**Comment by xuan-nguyen-swe** [comment] 2023-01-29 16:14
Ok, so we only support implicit multiplication in some cases.
But, then it should throw ParseExpection if the expression is invalid.

I tested the same expressions in 2.7 and 3.0.1. The older version behaves correctly if the expression is invalid.

```
// com.udojava:EvalEx:2.7

  Expression("2ab(a+b)").toRPN() // ExpressionException (good)
  Expression("2ab*(a+b)").toRPN() // ExpressionException (good)
  Expression("2a*b*(a+b)").toRPN() // ExpressionException (good)
  Expression("2*a*b*(a+b)").toRPN() // Pass (good)
  Expression("2*a*b*(a+b)").with("a", BigDecimal(3.5)).with("b", BigDecimal(2.5)).eval() // 105 (correct)
  Expression("2a").toRPN() // ExpressionException (good)
```

```
// com.ezylang:EvalEx:3.0.1

    Expression("2ab(a+b)").validate() // ParseException (good)
    Expression("2ab*(a+b)").validate() // Pass (bad)
    Expression("2a*b*(a+b)").validate() // Pass (bad)
    Expression("2a*b*(a+b)").with("a", BigDecimal(3.5)).with("b", BigDecimal(2.5)).evaluate().numberValue // 52.5 (bad)
    Expression("2*a*b*(a+b)").validate() // Pass (good)
    Expression("2*a*b*(a+b)").with("a", BigDecimal(3.5)).with("b", BigDecimal(2.5)).evaluate().numberValue // 105 (correct)
    Expression("2a").validate() // Pass (bad)
    Expression("2a").with("a", BigDecimal(3.5)).evaluate().numberValue // 3.5 (bad)
```

Could you correct the behavior in EvalEx 3?

**Comment by uklimaschewski** [comment] 2023-02-12 14:33
I will bring back the 2.x behavior.
You mention, that ` Expression("2ab(a+b)").toRPN()` tested good, but that is not the case. Also in 2.x this fails with an `Unknown function ab` exception.

**Closed** 2023-02-12 15:09 UTC
Labels: bug

**Comment by xuan-nguyen-swe** [comment] 2023-02-12 19:18
I didn't check the details error message. I only mean that the expectation to get exception is good.
Yes, I agree that the error message should be correct too.
